# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\new_shopping_list_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window_create_new_shopping_list(object):
    def setupUi(self, window_create_new_shopping_list):
        window_create_new_shopping_list.setObjectName("window_create_new_shopping_list")
        window_create_new_shopping_list.resize(692, 590)
        self.layout_new_shoppint_list_window = QtWidgets.QWidget(window_create_new_shopping_list)
        self.layout_new_shoppint_list_window.setObjectName("layout_new_shoppint_list_window")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layout_new_shoppint_list_window)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.layout_inner_new_shopping_list_window = QtWidgets.QHBoxLayout()
        self.layout_inner_new_shopping_list_window.setObjectName("layout_inner_new_shopping_list_window")
        self.table_widget_items = QtWidgets.QTableWidget(self.layout_new_shoppint_list_window)
        self.table_widget_items.setObjectName("table_widget_items")
        self.table_widget_items.setColumnCount(0)
        self.table_widget_items.setRowCount(0)
        self.layout_inner_new_shopping_list_window.addWidget(self.table_widget_items)
        self.layout_right = QtWidgets.QVBoxLayout()
        self.layout_right.setObjectName("layout_right")
        self.list_widget_shopping_list = QtWidgets.QListView(self.layout_new_shoppint_list_window)
        self.list_widget_shopping_list.setObjectName("list_widget_shopping_list")
        self.layout_right.addWidget(self.list_widget_shopping_list)
        self.layout_right_inputs = QtWidgets.QFormLayout()
        self.layout_right_inputs.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.layout_right_inputs.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.layout_right_inputs.setObjectName("layout_right_inputs")
        self.label = QtWidgets.QLabel(self.layout_new_shoppint_list_window)
        self.label.setObjectName("label")
        self.layout_right_inputs.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txt_item_idx = QtWidgets.QLineEdit(self.layout_new_shoppint_list_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_item_idx.sizePolicy().hasHeightForWidth())
        self.txt_item_idx.setSizePolicy(sizePolicy)
        self.txt_item_idx.setObjectName("txt_item_idx")
        self.layout_right_inputs.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_item_idx)
        self.label_2 = QtWidgets.QLabel(self.layout_new_shoppint_list_window)
        self.label_2.setObjectName("label_2")
        self.layout_right_inputs.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txt_item_amount = QtWidgets.QLineEdit(self.layout_new_shoppint_list_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_item_amount.sizePolicy().hasHeightForWidth())
        self.txt_item_amount.setSizePolicy(sizePolicy)
        self.txt_item_amount.setObjectName("txt_item_amount")
        self.layout_right_inputs.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_item_amount)
        self.layout_right.addLayout(self.layout_right_inputs)
        self.layout_right_buttons = QtWidgets.QHBoxLayout()
        self.layout_right_buttons.setObjectName("layout_right_buttons")
        self.button_add_item = QtWidgets.QPushButton(self.layout_new_shoppint_list_window)
        self.button_add_item.setObjectName("button_add_item")
        self.layout_right_buttons.addWidget(self.button_add_item)
        self.button_delete_item = QtWidgets.QPushButton(self.layout_new_shoppint_list_window)
        self.button_delete_item.setObjectName("button_delete_item")
        self.layout_right_buttons.addWidget(self.button_delete_item)
        self.button_clear_shopping_list = QtWidgets.QPushButton(self.layout_new_shoppint_list_window)
        self.button_clear_shopping_list.setObjectName("button_clear_shopping_list")
        self.layout_right_buttons.addWidget(self.button_clear_shopping_list)
        self.layout_right.addLayout(self.layout_right_buttons)
        self.layout_inner_new_shopping_list_window.addLayout(self.layout_right)
        self.horizontalLayout_3.addLayout(self.layout_inner_new_shopping_list_window)
        window_create_new_shopping_list.setCentralWidget(self.layout_new_shoppint_list_window)

        self.retranslateUi(window_create_new_shopping_list)
        QtCore.QMetaObject.connectSlotsByName(window_create_new_shopping_list)

    def retranslateUi(self, window_create_new_shopping_list):
        _translate = QtCore.QCoreApplication.translate
        window_create_new_shopping_list.setWindowTitle(_translate("window_create_new_shopping_list", "MainWindow"))
        self.label.setText(_translate("window_create_new_shopping_list", "Item index"))
        self.txt_item_idx.setText(_translate("window_create_new_shopping_list", "1"))
        self.label_2.setText(_translate("window_create_new_shopping_list", "Item quantity"))
        self.txt_item_amount.setText(_translate("window_create_new_shopping_list", "1"))
        self.button_add_item.setText(_translate("window_create_new_shopping_list", "Add item"))
        self.button_delete_item.setText(_translate("window_create_new_shopping_list", "Delete item"))
        self.button_clear_shopping_list.setText(_translate("window_create_new_shopping_list", "Clear shopping list"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window_create_new_shopping_list = QtWidgets.QMainWindow()
    ui = Ui_window_create_new_shopping_list()
    ui.setupUi(window_create_new_shopping_list)
    window_create_new_shopping_list.show()
    sys.exit(app.exec_())
