# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\beta_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from PyQt5.QtWidgets import QTableWidgetItem
import algorithm

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1125, 892)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 110, 172, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.layout_parameters = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.layout_parameters.setContentsMargins(0, 0, 0, 0)
        self.layout_parameters.setObjectName("layout_parameters")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setObjectName("label")
        self.layout_parameters.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txt_population_size = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_population_size.setEnabled(True)
        self.txt_population_size.setObjectName("txt_population_size")
        self.layout_parameters.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_population_size)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.layout_parameters.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txt_parents_percentage = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_parents_percentage.setObjectName("txt_parents_percentage")
        self.layout_parameters.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_parents_percentage)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.layout_parameters.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.txt_mutation_chance = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_mutation_chance.setObjectName("txt_mutation_chance")
        self.layout_parameters.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_mutation_chance)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.layout_parameters.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.txt_generation_number = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_generation_number.setObjectName("txt_generation_number")
        self.layout_parameters.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txt_generation_number)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 480, 91, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layout_cross = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layout_cross.setContentsMargins(0, 0, 0, 0)
        self.layout_cross.setObjectName("layout_cross")
        self.radio_cro_every_2nd = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radio_cro_every_2nd.setObjectName("radio_cro_every_2nd")
        self.layout_cross.addWidget(self.radio_cro_every_2nd)
        self.radio_cro_basic_rows_idx = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radio_cro_basic_rows_idx.setObjectName("radio_cro_basic_rows_idx")
        self.layout_cross.addWidget(self.radio_cro_basic_rows_idx)
        self.radio_cro_basic_rows_number = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radio_cro_basic_rows_number.setObjectName("radio_cro_basic_rows_number")
        self.layout_cross.addWidget(self.radio_cro_basic_rows_number)
        self.radio_cro_basic_rows_idx_and_number = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radio_cro_basic_rows_idx_and_number.setChecked(True)
        self.radio_cro_basic_rows_idx_and_number.setObjectName("radio_cro_basic_rows_idx_and_number")
        self.layout_cross.addWidget(self.radio_cro_basic_rows_idx_and_number)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(24, 380, 81, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.layout_mutation = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.layout_mutation.setContentsMargins(0, 0, 0, 0)
        self.layout_mutation.setObjectName("layout_mutation")
        self.radio_mut_singular = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radio_mut_singular.setChecked(True)
        self.radio_mut_singular.setObjectName("radio_mut_singular")
        self.layout_mutation.addWidget(self.radio_mut_singular)
        self.radio_mut_elimination = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radio_mut_elimination.setObjectName("radio_mut_elimination")
        self.layout_mutation.addWidget(self.radio_mut_elimination)
        # User
        self.button_start = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.gui_main_fun())
        self.button_start.setGeometry(QtCore.QRect(50, 30, 75, 23))
        self.button_start.setObjectName("button_start")
        self.button_restart = QtWidgets.QPushButton(self.centralwidget)
        self.button_restart.setGeometry(QtCore.QRect(40, 820, 75, 23))
        self.button_restart.setObjectName("button_restart")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(180, 10, 921, 881))
        self.tabWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.widget_charts = QtWidgets.QWidget()
        self.widget_charts.setObjectName("widget_charts")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.widget_charts)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 911, 851))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.layout_charts = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.layout_charts.setContentsMargins(0, 0, 0, 0)
        self.layout_charts.setObjectName("layout_charts")
        self.frame_discount = QtWidgets.QFrame(self.verticalLayoutWidget_5)
        self.frame_discount.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_discount.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_discount.setObjectName("frame_discount")
        self.layout_charts.addWidget(self.frame_discount)

        # DISCOUNT CHART
        self.layout_horizontal_discount_chart = QtWidgets.QHBoxLayout(self.frame_discount)
        self.layout_horizontal_discount_chart.setObjectName("layout_horizontal_discount_chart")
        self.figure_charts = plt.figure()
        self.canvas_discount = FigureCanvas(self.figure_charts)
        self.layout_horizontal_discount_chart.addWidget(self.canvas_discount)

        self.frame_delivery = QtWidgets.QFrame(self.verticalLayoutWidget_5)
        self.frame_delivery.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_delivery.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_delivery.setObjectName("frame_delivery")
        self.layout_charts.addWidget(self.frame_delivery)

        # DELIVERY CHART
        self.layout_horizontal_delivery_chart = QtWidgets.QHBoxLayout(self.frame_delivery)
        self.layout_horizontal_delivery_chart.setObjectName("layout_horizontal_delivery_chart")
        self.canvas_delivery = FigureCanvas(self.figure_charts)
        self.layout_horizontal_delivery_chart.addWidget(self.canvas_delivery)

        self.tabWidget.addTab(self.widget_charts, "")
        self.widget_algorithm = QtWidgets.QWidget()
        self.widget_algorithm.setObjectName("widget_algorithm")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.widget_algorithm)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 911, 851))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.layout_algorithm = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.layout_algorithm.setContentsMargins(0, 0, 0, 0)
        self.layout_algorithm.setObjectName("layout_algorithm")
        self.frame_algorithm = QtWidgets.QFrame(self.verticalLayoutWidget_4)
        self.frame_algorithm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_algorithm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_algorithm.setObjectName("frame_algorithm")
        self.layout_algorithm.addWidget(self.frame_algorithm)

        # ALGORITHM CHART
        self.layout_horizontal_algorithm_chart = QtWidgets.QHBoxLayout(self.frame_algorithm)
        self.layout_horizontal_algorithm_chart.setObjectName("layout_horizontal_algorithm_chart")
        self.figure_algorithm = plt.figure(1)
        self.canvas_algorithm = FigureCanvas(self.figure_algorithm)
        self.layout_horizontal_algorithm_chart.addWidget(self.canvas_algorithm)

        self.tabWidget.addTab(self.widget_algorithm, "")
        self.widget_solution_matrix = QtWidgets.QWidget()
        self.widget_solution_matrix.setObjectName("widget_solution_matrix")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.widget_solution_matrix)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(0, 0, 911, 851))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.layout_solution_matrix = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.layout_solution_matrix.setContentsMargins(0, 0, 0, 0)
        self.layout_solution_matrix.setObjectName("layout_solution_matrix")
        self.table_widget_solution_matrix = QtWidgets.QTableWidget(self.verticalLayoutWidget_7)
        self.table_widget_solution_matrix.setObjectName("table_widget_solution_matrix")
        self.layout_solution_matrix.addWidget(self.table_widget_solution_matrix)
        self.tabWidget.addTab(self.widget_solution_matrix, "")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 80, 101, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 460, 101, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 360, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 630, 61, 16))
        self.label_10.setObjectName("label_10")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 650, 83, 101))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.layout_mutation_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.layout_mutation_3.setContentsMargins(0, 0, 0, 0)
        self.layout_mutation_3.setObjectName("layout_mutation_3")
        self.radio_sel_tournament = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radio_sel_tournament.setChecked(True)
        self.radio_sel_tournament.setObjectName("radio_sel_tournament")
        self.layout_mutation_3.addWidget(self.radio_sel_tournament)
        self.radio_sel_roulette = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radio_sel_roulette.setObjectName("radio_sel_roulette")
        self.layout_mutation_3.addWidget(self.radio_sel_roulette)
        self.radio_sel_ranking = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radio_sel_ranking.setObjectName("radio_sel_ranking")
        self.layout_mutation_3.addWidget(self.radio_sel_ranking)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(30, 270, 64, 65))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.layout_algorithm_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.layout_algorithm_2.setContentsMargins(0, 0, 0, 0)
        self.layout_algorithm_2.setObjectName("layout_algorithm_2")
        self.radio_con_left = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.radio_con_left.setChecked(True)
        self.radio_con_left.setObjectName("radio_con_left")
        self.layout_algorithm_2.addWidget(self.radio_con_left)
        self.radio_con_random = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.radio_con_random.setChecked(False)
        self.radio_con_random.setObjectName("radio_con_random")
        self.layout_algorithm_2.addWidget(self.radio_con_random)
        self.radio_con_holder = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        # USER
        self.radio_con_holder.toggled.connect(self.radio_holder_set)

        self.radio_con_holder.setChecked(False)
        self.radio_con_holder.setObjectName("radio_con_holder")
        self.layout_algorithm_2.addWidget(self.radio_con_holder)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 250, 91, 16))
        self.label_13.setObjectName("label_13")
        self.button_create_matrix = QtWidgets.QPushButton(self.centralwidget)
        self.button_create_matrix.setEnabled(False)
        self.button_create_matrix.setGeometry(QtCore.QRect(110, 290, 61, 31))
        self.button_create_matrix.setCheckable(False)
        self.button_create_matrix.setObjectName("button_create_matrix")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Population size"))
        self.txt_population_size.setText(_translate("MainWindow", "100"))
        self.label_2.setText(_translate("MainWindow", "Parents [%]"))
        self.txt_parents_percentage.setText(_translate("MainWindow", "2"))
        self.label_3.setText(_translate("MainWindow", "Crossover chance [%]"))
        self.txt_mutation_chance.setText(_translate("MainWindow", "10"))
        self.label_4.setText(_translate("MainWindow", "Number of generations"))
        self.txt_generation_number.setText(_translate("MainWindow", "1000"))
        self.radio_cro_every_2nd.setText(_translate("MainWindow", "Every 2nd"))
        self.radio_cro_basic_rows_idx.setText(_translate("MainWindow", "Basic idx"))
        self.radio_cro_basic_rows_number.setText(_translate("MainWindow", "Basic number"))
        self.radio_cro_basic_rows_idx_and_number.setText(_translate("MainWindow", "Basic both"))
        self.radio_mut_singular.setText(_translate("MainWindow", "Singular"))
        self.radio_mut_elimination.setText(_translate("MainWindow", "Elimination"))
        self.button_start.setText(_translate("MainWindow", "START"))
        self.button_restart.setText(_translate("MainWindow", "RESTART"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget_charts), _translate("MainWindow", "Charts"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget_algorithm), _translate("MainWindow", "Algorithm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget_solution_matrix), _translate("MainWindow", "Solution Matrix"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Parameters</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Crossover</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Mutate</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Selection</span></p></body></html>"))
        self.radio_sel_tournament.setText(_translate("MainWindow", "Tournament"))
        self.radio_sel_roulette.setText(_translate("MainWindow", "Roulette"))
        self.radio_sel_ranking.setText(_translate("MainWindow", "Ranking"))
        self.radio_con_left.setText(_translate("MainWindow", "Left"))
        self.radio_con_random.setText(_translate("MainWindow", "Random"))
        self.radio_con_holder.setText(_translate("MainWindow", "Holder"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600;\">Construction<br/></span></p><p align=\"center\"><br/></p></body></html>"))
        self.button_create_matrix.setText(_translate("MainWindow", "Create"))

    def radio_holder_set(self):
        if self.radio_con_holder.isChecked():
            self.txt_population_size.setEnabled(False)
            self.button_create_matrix.setEnabled(True)
        else:
            self.txt_population_size.setEnabled(True)
            self.button_create_matrix.setEnabled(False)

    def prepare_gui_parameters(self):
        # PARAMETERS
        algorithm.population_size = int(self.txt_population_size.text())
        algorithm.parent_percentage = int(self.txt_parents_percentage.text()) / 100
        # TODO: Change txt_mutation_chance -> txt_crossover_chance
        algorithm.chance_to_crossover = int(self.txt_mutation_chance.text()) / 100
        algorithm.max_iters = int(self.txt_generation_number.text())
        # CONSTRUCTION
        # TODO: Implement it
        # Mutate
        if self.radio_mut_singular.isChecked():
            algorithm.mutation_type = 'singular'
        elif self.radio_mut_elimination.isChecked():
            algorithm.mutation_type = 'elimination'
        # Crossover
        if self.radio_cro_every_2nd.isChecked():
            algorithm.crossover_method = 'every_2nd'
        elif self.radio_cro_basic_rows_idx.isChecked():
            algorithm.crossover_method = ('basic', 'rows_idx')
        elif self.radio_cro_basic_rows_number.isChecked():
            algorithm.crossover_method = ('basic', 'rows_number')
        elif self.radio_cro_basic_rows_idx_and_number.isChecked():
            algorithm.crossover_method = ('basic', 'rows_idx_and_number')
        # Selection
        if self.radio_sel_tournament.isChecked():
            algorithm.selection_method = 'tournament'
        elif self.radio_sel_roulette.isChecked():
            algorithm.selection_method = 'roulette'
        elif self.radio_sel_ranking.isChecked():
            algorithm.selection_method = 'ranking'
        print('Chosen parameters:')
        print(f'population_size: {algorithm.population_size}')
        print(f'parent_percentage: {algorithm.parent_percentage}')
        print(f'chance_to_crossover: {algorithm.chance_to_crossover}')
        print(f'max_iters: {algorithm.max_iters}')
        print(f'mutation_type: {algorithm.mutation_type}')
        print(f'crossover_method: {algorithm.crossover_method}')
        print(f'selection_method: {algorithm.selection_method}')

    def create_solution_matrix_tab(self):
        products = [f'product_{i}' for i in range(20)]
        sellers = [f'seller_{i}' for i in range(20)]
        self.table_widget_solution_matrix.setRowCount(len(products))
        self.table_widget_solution_matrix.setColumnCount(len(sellers))
        for i in range(len(products)):
            for j in range(len(sellers)):
                self.table_widget_solution_matrix.setItem(i, j, QTableWidgetItem(str((i, j))))

    def create_algorithm_chart_tab(self):
        self.figure_algorithm.clear()
        oranges = ['9', '10', '11', '12']
        oranges_values = [90, 100, 110, 120]
        plt.bar(oranges, oranges_values, color='purple', width=0.4)
        plt.xlabel('orangesx')
        plt.ylabel('orangesy')
        plt.title('oranges')
        self.canvas_algorithm.draw()

    def create_charts_tab(self):
        self.figure_charts.clear()
        apples = ['1', '2', '3', '4']
        bananas = ['5', '6', '7', '8']
        apples_values = [10, 20, 30, 40]
        bananas_values = [50, 60, 70, 80]
        plt.bar(apples, apples_values, color='red', width=0.4)
        plt.xlabel('applesx')
        plt.ylabel('applesy')
        plt.title('apples')
        self.canvas_discount.draw()
        self.figure_charts.clear()
        plt.xlabel('bananasx')
        plt.ylabel('bananasy')
        plt.title('bananas')
        plt.bar(bananas, bananas_values, color='blue', width=0.4)
        self.canvas_delivery.draw()

    def gui_main_fun(self):
        self.prepare_gui_parameters()
        self.create_algorithm_chart_tab()
        self.create_solution_matrix_tab()
        self.create_charts_tab()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())